"""posts table

Revision ID: 305a2e468312
Revises: 79e0ad4ca8e0
Create Date: 2022-10-28 11:44:05.067132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '305a2e468312'
down_revision = '79e0ad4ca8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
