"""add foreign key

Revision ID: 600ea334339f
Revises: 60c1e82f2a6a
Create Date: 2022-10-19 12:27:37.942677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600ea334339f'
down_revision = '60c1e82f2a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['poster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'poster_id')
    # ### end Alembic commands ###
